### ISSUE TITLE
Jest configuration

### ISSUE THREAD

**Issue by Spell2az** [chingu-voyage6/Geckos-Team-04#9]
Setup Jest, for unit testing with agreed  coverage threshold.

**Comment by butteredtoast** [comment]
`react-scripts` is configured to use Jest by default. We may not need to add anything else in order to make this work:

![react-scripts-jest.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1f612c9a30f40012b8d984/125516c66e82c728ace21e0d46fa919b2096ceba8cfbb653b04ebd9e2c5533316546b3397f8fe62bab0021435a0d4ff9135e5c40faaa8c7faee03c70885409e5d03b0e73d42103eee9dc4be05ce36ade0d97bcae8b4bcae93827ee828c4b361a071889f74f78.png)

**Comment by Spell2az** [comment]
True, but coverage threshold should be added, to support our target coverage.
